version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: glenv
    main: ./cmd/glenv
    binary: glenv
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: glenv
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    formats:
      - tar.gz

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  disable: true

release:
  header: |
    ## What's New

    See [CHANGELOG.md](https://github.com/ohmylock/glenv/blob/main/CHANGELOG.md) for full details.
  footer: |
    ---
    **Full Changelog**: https://github.com/ohmylock/glenv/blob/main/CHANGELOG.md
